function norms = lagNorms(self)
% Return a vector of norm(self.getGram(lag)) at lag = 0..L-1
%   norms = lagNorms(self)
%
% Returns:
%   norms   [L x 1] vector of norm(self.getGram(lag)) for lag = 0..L-1
%
% Two things to keep in mind:
% * The norm for a given lag is norms(lag+1), since array indices start at 1
% * This only looks at kernel family r=1, under the assumption that the behavior
%   of the other kernel families is essentially the same. This is a reasonable
%   assumption when the kernel families are generated by an Interpolator, as is
%   the case in spkdec.SpikeBasis.toGram().

% Use the cached result if available
if ~isempty(self.lag_norms)
    norms = self.lag_norms;
else
    % Compute the norms
    lags = (0:self.L-1)';
    norms = arrayfun(@(lag) norm(self.getGram(lag)), lags);
    % Cache the result
    self.lag_norms = norms;
end

end
